import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Edit3, Flame, Target, Trash2 } from "lucide-react";
import { format } from "date-fns";
import { prisma } from "@/lib/prisma";
import { getDemoUser } from "@/lib/user";
import { calculateStreakStats } from "@/lib/streak-calculator";
import { ActivityHeatmap } from "@/components/ActivityHeatmap";
import { ConsistencyCharts } from "@/components/ConsistencyCharts";
import { HabitForm } from "@/components/HabitForm";

export default async function HabitDetail({ params }: { params: { id: string } }) { const user = await getDemoUser(); const habit = await prisma.habit.findFirst({ where: { id: params.id, userId: user.id }, include: { completions: { orderBy: { date: "asc" } } } }); if (!habit) notFound(); const stats = calculateStreakStats(habit.completions, habit.targetCount, habit.frequency as "DAILY" | "WEEKLY"); return <main className="page-shell"><header className="flex items-center justify-between"><Link href="/" className="button-secondary"><ArrowLeft size={15} /> Dashboard</Link><div className="flex gap-2"><Link href={`/habits/${habit.id}/edit`} className="icon-button" aria-label="Edit habit"><Edit3 size={16} /></Link><form action={`/api/habits/${habit.id}`} method="post"><button className="icon-button text-coral" aria-label="Archive habit"><Trash2 size={16} /></button></form></div></header><section className="py-12"><div className="mb-5 flex items-center gap-3"><span className="h-4 w-4 rounded-full" style={{ backgroundColor: habit.color }} /><span className="label">{habit.category} · {habit.frequency === "WEEKLY" ? "Weekly" : "Daily"}</span></div><h1 className="font-display text-4xl font-bold sm:text-6xl">{habit.title}</h1><p className="mt-4 max-w-xl text-muted">{habit.description || `A ${habit.targetCount} ${habit.targetUnit} practice.`}</p></section><div className="mb-8 grid gap-4 sm:grid-cols-4"><Stat icon={<Flame size={17} />} value={String(stats.currentStreak)} label="Current streak" /><Stat icon={<Flame size={17} />} value={String(stats.longestStreak)} label="Longest streak" /><Stat icon={<Target size={17} />} value={String(stats.totalCompletions)} label="Completions" /><Stat icon={<Target size={17} />} value={`${stats.completionRate}%`} label="Completion rate" /></div><ActivityHeatmap completions={habit.completions} targetCount={habit.targetCount} title={`${habit.title} activity`} /><ConsistencyCharts completions={habit.completions} targetCount={habit.targetCount} /><section className="mt-8 panel p-6"><p className="label">Habit details</p><div className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><div><span className="text-muted">Target</span><p className="mt-1 font-bold">{habit.targetCount} {habit.targetUnit}</p></div><div><span className="text-muted">Started</span><p className="mt-1 font-bold">{format(habit.createdAt, "MMM d, yyyy")}</p></div><div><span className="text-muted">Tracked days</span><p className="mt-1 font-bold">{habit.completions.length}</p></div></div></section></main>; }
function Stat({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="panel p-5"><span className="text-lime">{icon}</span><p className="mt-3 font-display text-2xl font-bold">{value}</p><p className="text-xs font-bold uppercase tracking-wider text-muted">{label}</p></div>; }